### ISSUE TITLE
Purpose of the website

### ISSUE THREAD

**Issue by arthurvguide** [arthurvguide/ask-japanese#1]
As a **user** I can **understand the purpose of the website** so that **I use its features**

### Acceptance Criteria
* Acceptance Criteria 1: User can navigate through the home page
* Acceptance Criteria 2: User can navigate to a contact page
* Acceptance Criteria 3: User can navigate to a book page 

### Tasks
- [ ] Install necessary Django modules and packages
- [ ] Configure settings
- [ ] Perform initial deployment
- [ ] Create wireframe and design to the home page
- [ ] Create templates for base, home, contact, and book pages and their styles
- [ ] Create views for home, contact, and book pages
