### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by arthurvguide** [arthurvguide/ask-japanese#11]
As a **user** I can **navigate throw the home page** so that **I get to know the restaurant and its offers**

### Acceptance Criteria
* Acceptance Criteria 1: User can read an about us section
* Acceptance Criteria 2: User can find general information about the restaurant
* Acceptance Criteria 3: User can navigate to menu, book, contact

### Tasks
- [ ] Task 1: Create, add content and style a hero section
- [ ] Task 2: Create, add content and style an about us section
- [ ] Task 3: Add general content
- [ ] Task 4: Call user to action
- [ ] Task 5: Create a marketing plan
