### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by arthurvguide** [arthurvguide/ask-japanese#12]
As a **user** I can **visit the menu page** so that **I know the dishes from the restaurant**

### Acceptance Criteria
* Acceptance Criteria 1: Each dish has its own image
* Acceptance Criteria 2: Filter for each menu section
* Acceptance Criteria 3: Menu in a Grid layout 

### Tasks
- [ ] Task 1: Create a wireframe and design for the menu page
- [ ] Task 2: Create a hero image
- [ ] Task 3: Create a menu grid for the items
