### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by arthurvguide** [arthurvguide/ask-japanese#4]
As a **user** I can **contact the restaurant team** so that **clarify any doubts**

### Acceptance Criteria
* Acceptance Criteria 1: User can input their details and queries 
* Acceptance Criteria 3: User details must include: Name, Last Name, Phone Number, Email, and Message

### Tasks
- [ ] Task 1: Create a wireframe to the contact page
- [ ] Task 2: Design and Style the contact page
- [ ] Task 3: Create a contact form
