### ISSUE TITLE
An automatic reply when contacting restaurant 

### ISSUE THREAD

**Issue by arthurvguide** [arthurvguide/ask-japanese#5]
As a **user** I can **receive an automatic email** for me **to be sure my message was sent**

### Acceptance Criteria
* Acceptance Criteria 1: Restaurant team will receive user messages through email
* Acceptance Criteria 2: User will receive an automatic reply
* Acceptance Criteria 3:  If the form is not valid, show an error to the user

### Tasks
- [ ] Task 1: Create an email to the restaurant owner/admin
- [ ] Task 2: Connect the contact form with EmailJs ( or other technology)
- [ ] Task 3: Validate form and show up any errors to the user
