### ISSUE TITLE
User book a visit

### ISSUE THREAD

**Issue by arthurvguide** [arthurvguide/ask-japanese#6]
As a **user** I can **make a booking** so that **I will visit the restaurant for a meal**

### Acceptance Criteria
* Acceptance Criteria 1: A booking must include Full Name, Date, Time, Party Size 
* Acceptance Criteria 2: A confirmation message must be displayed to the user

### Tasks
- [ ] Task 1:  Create a model for booking 
- [ ] Task 2:  Create a view for booking
- [ ] Task 3: Make migrate
- [ ] Task 4: Test
