### ISSUE TITLE
Admin manage tables

### ISSUE THREAD

**Issue by arthurvguide** [arthurvguide/ask-japanese#9]
As an **admin** I can **manage tables** so that **tables available will be presented**

### Acceptance Criteria
* Acceptance Criteria 1: Admin can create tables and define the size
* Acceptance Criteria 2: Admin can delete tables
* Acceptance Criteria 3: Admin can update table size

### Tasks
- [ ] Task 1:  Create a superuser
- [ ] Task 2:  Create model for tables
- [ ] Task 3: Make migrate
